### DISCUSSION TITLE
[Layout] Responsive props

### DISCUSSION THREAD

**Discussion by kyledurand** [Shopify/polaris-react#7500] [Ideas] [answered]
Let's discuss a couple options for setting responsive values in our layout components. In some cases it feels like over engineering to allow values to each of our 5 breakpoints. 

Take padding for instance:
`padding={{xs: '1', sm: '2', md: '3', lg: '4', xl: '5'}}`. This creates five custom properties that render every time this `Box` renders. It also relies on breakpoints added in css:

```css
--pc-box-padding-xs: var(--p-space-4);
--pc-box-padding-sm: var(--pc-box-padding-xs);
--pc-box-padding-md: var(--pc-box-padding-sm);
--pc-box-padding-lg: var(--pc-box-padding-md);
--pc-box-padding-xl: var(--pc-box-padding-lg);

padding: var(--pc-box-padding-xs);

@media #{$p-breakpoints-sm-up} {
  padding: var(--pc-box-padding-sm);
}

@media #{$p-breakpoints-md-up} {
  padding: var(--pc-box-padding-md);
}

@media #{$p-breakpoints-lg-up} {
  padding: var(--pc-box-padding-lg);
}

@media #{$p-breakpoints-xl-up} {
  padding: var(--pc-box-padding-xl);
}
```

This is a lot of overhead for something as simple as padding. How often are we or our consumers going to need different values at each of these breakpoints?

**Alternative solution:**

Use our breakpoint utility function:
```tsx
  const {smUp, mdUp, lgUp, xlUp} = useBreakpoints();

  const padding = () => {
    switch (true) {
      case xlUp:
        return '5';
      case lgUp:
        return '4';
      case mdUp:
        return '3';
      case smUp:
        return '2';
      default:
        return '1';
    }
  };
  return (
    <Box padding={padding()}>
  );
```

This is an extreme example where the consumer needs different values at each breakpoint where 99% of the time it would probably look more like this:

```tsx
<Box padding={mdUp ? '2' : '1'} />
```
Because layouts in the admin don't usually change padding at more than one breakpoint. 

There are drawbacks to each option here. One major one would be how difficult migrations would be where we'd have to import `useBreakpoints` and figure out the logic vs managing the props manually. 

I think the responsive props object is generally clearer but it does add a lot of overhead
