### ISSUE TITLE
Invalid CSS syntax in latest builds

### ISSUE THREAD

**Issue by aaronadamsCA** [Shopify/polaris-react#11784]
### Summary

Since Polaris v12.22.0, our app builds fail due to invalid CSS syntax in this package.

This file: https://unpkg.com/@shopify/polaris@12.22.1/build/esm/styles.css

Contains this code:

```css
@media (--p-breakpoints-md-up) and print{
    .Polaris-Frame--hasNav .Polaris-Frame__Main{
        padding-left:0;
    }
      }
```

### Expected behavior

The media query should be something valid, like `@media print and (min-width: 10px)`.

### Actual behavior

The invalid media query breaks our CSS preprocessing ([example](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Atrue%2C%22customMedia%22%3Atrue%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A6225920%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22%40media%20(--p-breakpoints-md-up)%20and%20print%7B%5Cn%20%20%20%20.Polaris-Frame--hasNav%20.Polaris-Frame__Main%7B%5Cn%20%20%20%20%20%20%20%20padding-left%3A0%3B%5Cn%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D%5Cn%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)).

### Are you using React components?

None

### Polaris version number

v12.22.1
