### ISSUE TITLE
[a11y] Nav focus difficult to see

### ISSUE THREAD

**Issue by dpersing** [Shopify/polaris-react#1747]
## Issue summary

The focus indicator for standard primary links relies on a very slight change in color from `#212b36` to `#202e78`, which is very difficult to see next to the the change in the icon color.

In comparison, the hover style relies on a change in background that creates more visual difference between the inactive and hover states.

As a result, what has focus and what gets hovered looks a bit different, which may cause confusion and may make what has focus unclear.

([2.4.7 Focus Visible](https://www.w3.org/TR/WCAG21/#focus-visible), Level A).

## Expected behavior

Hover and focus styles should match to provide additional visual change.

## Actual behavior

Default link style:

```
.Polaris-Navigation__Item {
    ...
    color: #212b36;
    ...
}
```

Hover style:

```CSS
.Polaris-Navigation__Item:hover {
    background-image: linear-gradient(rgba(223,227,232,.3),rgba(223,227,232,.3));
    color: #212b36;
    text-decoration: none;
}
```

<img width="365" alt="Hover style on 'Home' Link" src="https://user-images.githubusercontent.com/1462085/60923284-7460d880-a253-11e9-8f4a-1c41cc28086e.png">

Focus style:

```CSS
.Polaris-Navigation__Item:focus {
    color: #202e78;
}
```

<img width="195" alt="Focus style on 'Home' link" src="https://user-images.githubusercontent.com/1462085/60923057-f3a1dc80-a252-11e9-8b94-20f10dcbbbfc.png">

## Steps to reproduce the problem

1. Navigate to the nav examples: https://polaris.shopify.com/components/navigation/navigation
1. Use the mouse to hover over the primary links
1. Use the `Tab` key to move focus through the primary links
1. Compare with the secondary links

Secondary link focus state for comparison (icon focus is 4:11:1 against it background, which meets guidelines for non-text content):

<img width="261" alt="Secondary link focus state" src="https://user-images.githubusercontent.com/1462085/60214025-8edd8f80-9819-11e9-8ccc-09a5138ac1a7.png">

## Recommendation

Use both the hover and focus styles together for both states.

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 3.17.0+
- Browser: All
- Device: All
- Operating System: All
