### ISSUE TITLE
Option and actionlist component headers have incorrect font weight/type style

### ISSUE THREAD

**Issue by HYPD** [Shopify/polaris-react#2214]
## Issue summary

Action and option list headers use subheading text style but they arent bold.

## Expected behavior

Bold font weight:
<img width="269" alt="CleanShot 2019-09-30 at 11 55 44@2x" src="https://user-images.githubusercontent.com/970304/65895301-3fa77d80-e379-11e9-80cc-db73333be6a5.png">

## Actual behavior

Regular font weight:
<img width="260" alt="CleanShot 2019-09-30 at 11 56 22@2x" src="https://user-images.githubusercontent.com/970304/65895365-58b02e80-e379-11e9-8287-98feeea50891.png">

**Comment by skvale** [comment]
Looks like it's on purpose if the `scss` calls out `font-weight: 400`
```scss
// src/components/OptionList/OptionList.scss
.Title {
  @include text-style-subheading;
  padding: spacing(tight) spacing();
  border-bottom: border();
  font-weight: 400;
  color: color('ink', 'lighter');
}
```
