### ISSUE TITLE
Remove the need for an esnext/styles folder

### ISSUE THREAD

**Issue by BPScott** [Shopify/polaris-react#3009]
We've got a public sass API. It is built from the contents of [src/styles](https://github.com/Shopify/polaris-react/tree/master/src/styles).

However like our JS it has two built out representations:

- [`styles`](https://unpkg.com/browse/@shopify/polaris@4.22.0/styles/) is a plain version of this ready to be consumed by people not using css-modules.
- [`esnext/styles`](https://unpkg.com/browse/@shopify/polaris@4.22.0/esnext/styles/) is ready to be consumed by folks using css-modules - i.e. folks using sewing-kit.

What would it take to remove this duplication and have a single entrypoint to our public api, so we can stop telling internal and external folks to use two different file paths? Removing this split would also help remove some [build hackery](https://github.com/Shopify/polaris-react/blob/af016fb8b0b782587ade0fb5aa78b8f887a98131/config/rollup/plugins/styles.js#L150-L163).

Two things:

- We need to stop referencing the files in `esnext/styles` within our per-component files in the esnext folder.
- We need to remove any usage of postcss directives in `src/styles`. Currently our only usage of this is a use of `:global` to get at an animation name in [_skeleton.scss](https://github.com/Shopify/polaris-react/blob/af016fb8b0b782587ade0fb5aa78b8f887a98131/src/styles/shared/_skeleton.scss#L20).

To solve the first point #2938 will need to be merged. This will mean that these files won't be referenced by our other scss files in the esnext folder (or the css files if [css support in SK is added](https://github.com/Shopify/sewing-kit/pull/2109)). At which point the distribution of our public API is disconnected from the other files we ship - we can place and manipulate it however.

To solve the second point we can place the name of the animation into a css custom property after it is defined in [global.scss](https://github.com/Shopify/polaris-react/blob/af016fb8b0b782587ade0fb5aa78b8f887a98131/src/styles/global.scss#L66) (AppProvider.scss in v5) (idea inspired by [this article](https://gravitydept.com/blog/keyframe-animations-in-css-modules):

```scss
@keyframes :global(polaris-SkeletonShimmerAnimation) {
  0% { opacity: 0.45; }
  100% { opacity: 0.9; }
}

:root {
  --polaris-shimmer-animation-name: 'polaris-SkeletonShimmerAnimation';
}
```

And then the mixin in _skeleton.scss can be updated to reference the custom property

```scss
@mixin skeleton-shimmer {
  // The polaris-SkeletonShimmerAnimation property is defined in, defined in /src/styles/global.scss
  animation: var(--polaris-SkeletonShimmerAnimation) $skeleton-shimmer-duration linear infinite alternate;
  will-change: opacity;
}
```

If we're feeling clever we might want to stick that whole animation in the custom property instead of just the name.

This removes the one usage of css-modules parlance in our sass mixins. At which point we can:

- Remove our [build hackery](https://github.com/Shopify/polaris-react/blob/af016fb8b0b782587ade0fb5aa78b8f887a98131/config/rollup/plugins/styles.js#L150-L164) around creating the `styles` folder, and at which point the contents of styles and esnext/styles become identical.
- Update our build config so that we ship compiled scss files in src/components - and thus they no longer reference the `esnext/styles` folder
- Remove `esnext/styles` and point sewing-kit consumers towards consuming `styles/_public-api.scss` folder instead of `esnext/styles/_public-api.scss`
